repos:
  - repo: local
    hooks:
      - id: lint
        name: lint
        description: Run linters and formatters
        entry: make
        language: system
        types: [python]
        args:
          - lint
