[tool.black]
line-length = 120

[tool.isort]
profile = "black"
skip_glob = ["python/ansible/plugins"]
skip = ["python/init_db.py", "python/task_runner.py", "python/backupdb.py", "python/job_runner.py",
    "python/drf_docs.py"]

[tool.pylint.master]
ignore = ["migrations"]

[tool.pylint."messages control"]
disable = ["missing-docstring", "missing-timeout", "no-else-return", "no-member", "too-few-public-methods",
    "too-many-arguments"]
good-names = ["db", "e", "f", "i", "pk"]

[tool.pylint.format]
max-line-length = 120

[tool.pylint.similarities]
min-similarity-lines = 30

[tool.ruff]
line-length = 120
select = ["BLE", "COM", "C4", "C90", "DTZ", "F", "E", "N", "UP", "W", "YTT"]
exclude = ["migrations", "python/audit/cases/adcm.py", "python/audit/cases/cluster.py", "python/audit/cases/common.py",
    "python/audit/cases/config.py", "python/audit/cases/host_and_provider.py", "python/audit/cases/rbac.py",
    "python/audit/cases/service.py", "python/audit/cases/stack.py",
    "tests/ui_tests/app/page/common/configuration/page.py",
    "tests/functional/maintenance_mode/test_inventory_modification.py"]
