[tool.black]
line-length = 120

[tool.isort]
profile = "black"
skip_glob = ["python/ansible/plugins"]
skip = ["python/init_db.py", "python/task_runner.py", "python/backupdb.py", "python/job_runner.py",
    "python/drf_docs.py"]

[tool.pylint.master]
ignore = ["migrations"]

[tool.pylint."messages control"]
disable = ["abstract-method", "consider-using-with", "import-error", "missing-docstring", "missing-timeout",
    "no-else-return", "no-member", "too-few-public-methods", "too-many-arguments", "unused-argument"]
good-names = ["db", "e", "f", "i", "pk"]

[tool.pylint.format]
max-line-length = 120

[tool.pylint.similarities]
min-similarity-lines = 30
