version: 1
update_configs:
  - package_manager: "javascript"
    directory: "/web"
    update_schedule: "daily"
    target_branch: "develop"
    version_requirement_updates: "auto"
    allowed_updates:
      - match:
          update_type: "all"
          dependency_type: "all"

  - package_manager: "python"
    directory: "/"
    update_schedule: "daily"
    target_branch: "develop"
    version_requirement_updates: "auto"
    allowed_updates:
      - match:
          update_type: "all"
          dependency_type: "all"

  - package_manager: "go:modules"
    directory: "/go/adcm/"
    update_schedule: "daily"
    target_branch: "develop"
    allowed_updates:
      - match:
          update_type: "all"
          dependency_type: "all"